name: "Map GitHub user to Slack"
description: "Maps a GitHub username to a Slack username"
inputs:
  github_user:
    description: "GitHub username"
    required: true
outputs:
  slack_user:
    description: "Mapped Slack username"
    value: ${{ steps.map_github_user.outputs.slack_user }}
runs:
  using: "composite"
  steps:
    - name: Fetch Slack user from JSON
      id: map_github_user
      shell: bash
      run: |
        FILE_PATH="${{ github.workspace }}/github_to_slack.json"
        
        if [[ ! -f "$FILE_PATH" ]]; then
          echo "Error: File $FILE_PATH not found!" >&2
          exit 1
        fi

        FILE_CONTENT=$(cat "$FILE_PATH")
        SLACK_USER=$(echo "$FILE_CONTENT" | jq -r --arg user "${{ inputs.github_user }}" '.[$user] // "@"+$user')

        echo "slack_user=$SLACK_USER" >> $GITHUB_OUTPUT
