name: "Map GitHub user to Slack"
description: "Maps a GitHub username to a Slack username"
inputs:
  github_user:
    description: "GitHub username"
    required: true
outputs:
  slack_user:
    description: "Mapped Slack username"
    value: ${{ steps.map_github_user.outputs.slack_user }}
runs:
  using: "composite"
  steps:
    - name: Clone elementor-tests-configuration repository
      shell: bash
      run: |
        git clone https://github.com/elementor/elementor-tests-configuration.git config_repo

    - name: Fetch Slack user from JSON
      id: map_github_user
      shell: bash
      run: |
        FILE_PATH="config_repo/github_to_slack.json"
        if [[ ! -f "$FILE_PATH" ]]; then
          echo "Error: File $FILE_PATH not found!" >&2
          exit 1
        fi

        echo "DEBUG: Input github_user = '${{ inputs.github_user }}'"

        FILE_CONTENT=$(cat "$FILE_PATH")

        FILE_CONTENT=$(echo "$FILE_CONTENT" | sed '1s/^\xEF\xBB\xBF//')

        SLACK_USER=$(echo "$FILE_CONTENT" | jq -r --arg user "${{ inputs.github_user }}" '.[$user] // ("@" + $user)')

        echo "slack_user=$SLACK_USER" >> $GITHUB_OUTPUT
